// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearApplicationLogs() {
  return window['go']['ipc']['KubeBridge']['ClearApplicationLogs']();
}

export function CopyToClipboard(arg1) {
  return window['go']['ipc']['KubeBridge']['CopyToClipboard'](arg1);
}

export function DeleteConfigMap(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['DeleteConfigMap'](arg1, arg2);
}

export function DeletePod(arg1, arg2, arg3) {
  return window['go']['ipc']['KubeBridge']['DeletePod'](arg1, arg2, arg3);
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['DeleteSecret'](arg1, arg2);
}

export function ExecResize(arg1, arg2, arg3) {
  return window['go']['ipc']['KubeBridge']['ExecResize'](arg1, arg2, arg3);
}

export function ExecWrite(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['ExecWrite'](arg1, arg2);
}

export function GetApplicationLogs() {
  return window['go']['ipc']['KubeBridge']['GetApplicationLogs']();
}

export function GetClusterConfigCounts(arg1) {
  return window['go']['ipc']['KubeBridge']['GetClusterConfigCounts'](arg1);
}

export function GetClusterHealthInfo() {
  return window['go']['ipc']['KubeBridge']['GetClusterHealthInfo']();
}

export function GetClusterOverview() {
  return window['go']['ipc']['KubeBridge']['GetClusterOverview']();
}

export function GetConfigMapData(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['GetConfigMapData'](arg1, arg2);
}

export function GetConfigMaps(arg1) {
  return window['go']['ipc']['KubeBridge']['GetConfigMaps'](arg1);
}

export function GetContainerDetails(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['GetContainerDetails'](arg1, arg2);
}

export function GetContexts() {
  return window['go']['ipc']['KubeBridge']['GetContexts']();
}

export function GetControllerPods(arg1, arg2, arg3) {
  return window['go']['ipc']['KubeBridge']['GetControllerPods'](arg1, arg2, arg3);
}

export function GetCronJobs(arg1) {
  return window['go']['ipc']['KubeBridge']['GetCronJobs'](arg1);
}

export function GetDeployments(arg1) {
  return window['go']['ipc']['KubeBridge']['GetDeployments'](arg1);
}

export function GetIngresses(arg1) {
  return window['go']['ipc']['KubeBridge']['GetIngresses'](arg1);
}

export function GetInitialState() {
  return window['go']['ipc']['KubeBridge']['GetInitialState']();
}

export function GetJobLatestPod(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['GetJobLatestPod'](arg1, arg2);
}

export function GetJobs(arg1) {
  return window['go']['ipc']['KubeBridge']['GetJobs'](arg1);
}

export function GetNamespaces() {
  return window['go']['ipc']['KubeBridge']['GetNamespaces']();
}

export function GetNodes() {
  return window['go']['ipc']['KubeBridge']['GetNodes']();
}

export function GetPods(arg1) {
  return window['go']['ipc']['KubeBridge']['GetPods'](arg1);
}

export function GetResourceYAML(arg1, arg2, arg3) {
  return window['go']['ipc']['KubeBridge']['GetResourceYAML'](arg1, arg2, arg3);
}

export function GetSecretData(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['GetSecretData'](arg1, arg2);
}

export function GetSecrets(arg1) {
  return window['go']['ipc']['KubeBridge']['GetSecrets'](arg1);
}

export function GetServices(arg1) {
  return window['go']['ipc']['KubeBridge']['GetServices'](arg1);
}

export function GetStatefulSets(arg1) {
  return window['go']['ipc']['KubeBridge']['GetStatefulSets'](arg1);
}

export function GetWorkloadCache() {
  return window['go']['ipc']['KubeBridge']['GetWorkloadCache']();
}

export function RerunJob(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['RerunJob'](arg1, arg2);
}

export function RestartPod(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['RestartPod'](arg1, arg2);
}

export function SetCustomEmitter(arg1) {
  return window['go']['ipc']['KubeBridge']['SetCustomEmitter'](arg1);
}

export function SetNamespace(arg1) {
  return window['go']['ipc']['KubeBridge']['SetNamespace'](arg1);
}

export function SetWailsContext(arg1) {
  return window['go']['ipc']['KubeBridge']['SetWailsContext'](arg1);
}

export function StartLogStream(arg1) {
  return window['go']['ipc']['KubeBridge']['StartLogStream'](arg1);
}

export function StartPodExec(arg1) {
  return window['go']['ipc']['KubeBridge']['StartPodExec'](arg1);
}

export function StopLogStream(arg1) {
  return window['go']['ipc']['KubeBridge']['StopLogStream'](arg1);
}

export function StopPodExec(arg1) {
  return window['go']['ipc']['KubeBridge']['StopPodExec'](arg1);
}

export function SwitchContext(arg1) {
  return window['go']['ipc']['KubeBridge']['SwitchContext'](arg1);
}

export function TriggerCronJob(arg1, arg2) {
  return window['go']['ipc']['KubeBridge']['TriggerCronJob'](arg1, arg2);
}
