// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';
import {context} from '../models';

export function ClearApplicationLogs():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteConfigMap(arg1:string,arg2:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string,arg3:any):Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<void>;

export function ExecResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ExecWrite(arg1:string,arg2:string):Promise<void>;

export function GetApplicationLogs():Promise<Array<string>>;

export function GetClusterConfigCounts(arg1:string):Promise<ipc.ClusterConfigCounts>;

export function GetClusterHealthInfo():Promise<ipc.ClusterHealthInfo>;

export function GetClusterOverview():Promise<ipc.ClusterOverview>;

export function GetConfigMapData(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetConfigMaps(arg1:string):Promise<Array<ipc.ConfigMapSummary>>;

export function GetContainerDetails(arg1:string,arg2:string):Promise<Array<ipc.ContainerDetail>>;

export function GetContexts():Promise<Array<ipc.KubeContext>>;

export function GetControllerPods(arg1:string,arg2:string,arg3:string):Promise<Array<ipc.PodSummary>>;

export function GetCronJobs(arg1:string):Promise<Array<ipc.CronJobSummary>>;

export function GetDeployments(arg1:string):Promise<Array<ipc.DeploymentSummary>>;

export function GetIngresses(arg1:string):Promise<Array<ipc.IngressSummary>>;

export function GetInitialState():Promise<ipc.InitialBootstrapState>;

export function GetJobLatestPod(arg1:string,arg2:string):Promise<ipc.PodSummary>;

export function GetJobs(arg1:string):Promise<Array<ipc.JobSummary>>;

export function GetNamespaces():Promise<Array<ipc.Namespace>>;

export function GetNodes():Promise<Array<ipc.NodeSummary>>;

export function GetPods(arg1:string):Promise<Array<ipc.PodSummary>>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSecretData(arg1:string,arg2:string):Promise<Record<string, string>>;

export function GetSecrets(arg1:string):Promise<Array<ipc.SecretSummary>>;

export function GetServices(arg1:string):Promise<Array<ipc.ServiceSummary>>;

export function GetStatefulSets(arg1:string):Promise<Array<ipc.StatefulSetSummary>>;

export function GetWorkloadCache():Promise<ipc.WorkloadCache>;

export function RerunJob(arg1:string,arg2:string):Promise<ipc.JobSummary>;

export function RestartPod(arg1:string,arg2:string):Promise<void>;

export function SetCustomEmitter(arg1:ipc.EventEmitter):Promise<void>;

export function SetNamespace(arg1:string):Promise<void>;

export function SetWailsContext(arg1:context.Context):Promise<void>;

export function StartLogStream(arg1:ipc.LogStreamRequest):Promise<string>;

export function StartPodExec(arg1:ipc.ExecRequest):Promise<string>;

export function StopLogStream(arg1:string):Promise<void>;

export function StopPodExec(arg1:string):Promise<void>;

export function SwitchContext(arg1:string):Promise<void>;

export function TriggerCronJob(arg1:string,arg2:string):Promise<ipc.JobSummary>;
