// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetInitialState():Promise<ipc.InitialBootstrapState>;

export function Greet(arg1:string):Promise<string>;

export function SetKubeBridge(arg1:ipc.KubeBridge):Promise<void>;
